### PR TITLE
Update MobPlugin.java

### PR DESCRIPTION
**Pull request by sero583**
Fix typo

### CODE REVIEW

**Comment by PikyCZ** [comment]
oo Thanks :D ..

**Comment by sero583** [comment]
@PikyCZ No problem hahah

**Comment by PikyCZ** [comment]
@sero583  can you help me with AutoSpawnTask?

**Comment by sero583** [comment]
@PikyCZ where you need help? Extend the class a runnable (yes, from the java classes).

**Comment by PikyCZ** [comment]
:DD 
ok thanks

**Comment by sero583** [comment]
@PikyCZ If some help needed feel free to ask.

**Comment by PikyCZ** [comment]
discord?

**Comment by sero583** [comment]
@PikyCZ I do not have discord or ever think I will create an account, I'm fine in the comment seciton of GitHub.

**Comment by PikyCZ** [comment]
we create Nukkit Discord Chanel (better than gitter)

**Pull request merged**
