### PR TITLE
Fix enderman drops

### PR DESCRIPTION
**Pull request by qazedc1212**

### CODE REVIEW

**Comment by PikyCZ** [comment]
thanks

**Comment by qazedc1212** [comment]
entities/animal/WalkingAnimal.java
105,5
Method does not override or implement a method for a supertype 
Maybe add @Override before the string will fix

**Comment by PikyCZ** [comment]
@Override
    public boolean onInteract(Entity entity, Item item) {
?

2017-01-27 17:22 GMT+01:00 qazedc1212 <notifications@github.com>:

**Comment by qazedc1212** [comment]
For some reason CircleCI failed on that part, I will check now

**Comment by qazedc1212** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project MobPlugin: Compilation failure
[ERROR] /home/joe/MCPE/MobPlugin/src/main/java/creeperCZ/mobplugin/entities/animal/WalkingAnimal.java:[105,5] method does not override or implement a method from a supertype

**Pull request merged**
