### PR TITLE
Revert "The plugin now will probably works."

### PR DESCRIPTION
**Pull request by Asuna-Yuuki**
Reverts PikyCZ/MobPlugin#59

### CODE REVIEW

**Comment by shanwer** [comment]
WTF,Why there're two utils.java files in different packages?

**Comment by PikyCZ** [comment]
Blame your and yasuno work

**Comment by shanwer** [comment]
Me?Why?

**Comment by Asuna-Yuuki** [comment]
@PikyCZ  hmm why blame me I got but I leave alone

**Comment by Asuna-Yuuki** [comment]
you have it about me or someone else ? idk

**Comment by Asuna-Yuuki** [comment]
@PikyCZ

**Pull request merged**
