### PR TITLE
try to fix download [wip] dont merge when i say

### PR DESCRIPTION
**Pull request by caspervanneck**

### CODE REVIEW

**Comment by PikyCZ** [comment]
Thanks :) .. ok im wait for use version :DD

**Comment by caspervanneck** [comment]
i tink yo kan merge it

**Comment by caspervanneck** [comment]
@PikyCZ

**Comment by caspervanneck** [comment]
wait i gone test it i have maven @PikyCZ

**Comment by caspervanneck** [comment]
you can merge it now @PikyCZ or @Creeperface01

**Comment by PikyCZ** [comment]
ok thx :)

**Pull request merged**
